## ATPE-1%


In [19]:
import numpy as np

test = np.array([3, 1, 2, 4, 5])
print(np.argsort(test))
print(np.sort(test))
test[np.argsort(test) < 2]


[1 2 0 3 4]
[1 2 3 4 5]


array([3, 2])

In [ ]:
from pathlib import Path

base_1 = Path(
    "Transformer_NAR_[64-4-4-256-0.1]@daymet_4huc_t01_1980~1995#1995~2000#2000~2014@15|14+1[33+1]@NSELoss_n200_bs512_lr0.001_warm_up@seed1234")

base_2 = Path(
    "4huc_test_search/Transformer_NAR_[64-4-4-256-0.1]@daymet_4huc_t01_1980~1995#1995~2000#2000~2014@15|14+1[33+1]@NSELoss_n40_bs512_lr0.0002_warm_up@dp0.1@seed1234")

